spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/engineeros
spring.datasource.username=postgres
spring.datasource.password=sona3367

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true